/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/layout/AdminLayout.vue')['default']
    AndroidTutorials: typeof import('./src/components/tutorials/AndroidTutorials.vue')['default']
    AnimatedCharacter: typeof import('./src/components/AnimatedCharacter.vue')['default']
    ElAlert: typeof import('element-plus/es/components/alert/index.mjs')['ElAlert']
    ElAvatar: typeof import('element-plus/es/components/avatar/index.mjs')['ElAvatar']
    ElBadge: typeof import('element-plus/es/components/badge/index.mjs')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es/components/breadcrumb/index.mjs')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es/components/breadcrumb/index.mjs')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es/components/button/index.mjs')['ElButton']
    ElButtonGroup: typeof import('element-plus/es/components/button/index.mjs')['ElButtonGroup']
    ElCard: typeof import('element-plus/es/components/card/index.mjs')['ElCard']
    ElCheckbox: typeof import('element-plus/es/components/checkbox/index.mjs')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es/components/checkbox/index.mjs')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es/components/col/index.mjs')['ElCol']
    ElCollapse: typeof import('element-plus/es/components/collapse/index.mjs')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es/components/collapse/index.mjs')['ElCollapseItem']
    ElCollapseTransition: typeof import('element-plus/es/components/collapse-transition/index.mjs')['ElCollapseTransition']
    ElColorPicker: typeof import('element-plus/es/components/color-picker/index.mjs')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es/components/date-picker/index.mjs')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es/components/descriptions/index.mjs')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es/components/descriptions/index.mjs')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es/components/dialog/index.mjs')['ElDialog']
    ElDivider: typeof import('element-plus/es/components/divider/index.mjs')['ElDivider']
    ElDrawer: typeof import('element-plus/es/components/drawer/index.mjs')['ElDrawer']
    ElDropdown: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es/components/empty/index.mjs')['ElEmpty']
    ElForm: typeof import('element-plus/es/components/form/index.mjs')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index.mjs')['ElFormItem']
    ElIcon: typeof import('element-plus/es/components/icon/index.mjs')['ElIcon']
    ElImageViewer: typeof import('element-plus/es/components/image-viewer/index.mjs')['ElImageViewer']
    ElInput: typeof import('element-plus/es/components/input/index.mjs')['ElInput']
    ElInputNumber: typeof import('element-plus/es/components/input-number/index.mjs')['ElInputNumber']
    ElLink: typeof import('element-plus/es/components/link/index.mjs')['ElLink']
    ElMenu: typeof import('element-plus/es/components/menu/index.mjs')['ElMenu']
    ElMenuItem: typeof import('element-plus/es/components/menu/index.mjs')['ElMenuItem']
    ElOption: typeof import('element-plus/es/components/select/index.mjs')['ElOption']
    ElOptionGroup: typeof import('element-plus/es/components/select/index.mjs')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es/components/pagination/index.mjs')['ElPagination']
    ElProgress: typeof import('element-plus/es/components/progress/index.mjs')['ElProgress']
    ElRadio: typeof import('element-plus/es/components/radio/index.mjs')['ElRadio']
    ElRadioButton: typeof import('element-plus/es/components/radio/index.mjs')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es/components/radio/index.mjs')['ElRadioGroup']
    ElRow: typeof import('element-plus/es/components/row/index.mjs')['ElRow']
    ElSelect: typeof import('element-plus/es/components/select/index.mjs')['ElSelect']
    ElSkeleton: typeof import('element-plus/es/components/skeleton/index.mjs')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es/components/switch/index.mjs')['ElSwitch']
    ElTable: typeof import('element-plus/es/components/table/index.mjs')['ElTable']
    ElTableColumn: typeof import('element-plus/es/components/table/index.mjs')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es/components/tabs/index.mjs')['ElTabPane']
    ElTabs: typeof import('element-plus/es/components/tabs/index.mjs')['ElTabs']
    ElTag: typeof import('element-plus/es/components/tag/index.mjs')['ElTag']
    ElText: typeof import('element-plus/es/components/text/index.mjs')['ElText']
    ElTimeline: typeof import('element-plus/es/components/timeline/index.mjs')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es/components/timeline/index.mjs')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es/components/tooltip/index.mjs')['ElTooltip']
    ElUpload: typeof import('element-plus/es/components/upload/index.mjs')['ElUpload']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    IOSTutorials: typeof import('./src/components/tutorials/iOSTutorials.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    MacOSTutorials: typeof import('./src/components/tutorials/MacOSTutorials.vue')['default']
    MobileCardList: typeof import('./src/components/MobileCardList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoftwareTutorials: typeof import('./src/components/tutorials/SoftwareTutorials.vue')['default']
    UpgradeDevicesDrawer: typeof import('./src/components/UpgradeDevicesDrawer.vue')['default']
    UserLayout: typeof import('./src/components/layout/UserLayout.vue')['default']
    WindowsTutorials: typeof import('./src/components/tutorials/WindowsTutorials.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es/components/loading/index.mjs')['ElLoadingDirective']
  }
}
